
GET http://127.0.0.1:4000/tours

###

POST http://127.0.0.1:4000/tours
Content-Type: application/json

{
  "name": "Test Tour",
   "info": "This is a, Toyota",
   "image": "test-image.jpg",
   "price": 5,
   "duration": 2,
   "groupSize": 5,
   "rating": 5,
   "availability": true
}
###

GET http://127.0.0.1:4000/tours/1

###

PUT http://127.0.0.1:4000/tours/1
Content-Type: application/json

{
  "name": "Test Tour",
   "info": "This is a, Toyota",
   "image": "test-image.jpg",
   "price": 5,
   "duration": 2,
   "groupSize": 5,
   "rating": 5,
   "availability": false
}

###
DELETE http://127.0.0.1:4000/tours/1

###


GET http://127.0.0.1:4000/users

###

POST http://127.0.0.1:4000/users
Content-Type: application/json

{
  "name": "Matti Seppänen",
    "password": "M@45mtg$",
    "username": "mattis",
    "address": "Mannerheimintie 14, 00100 Helsinki",	
    "age": 23
}

###

GET http://127.0.0.1:4000/users/1

###

PUT http://127.0.0.1:4000/users/1
Content-Type: application/json

{
  "name": "Matti Seppänen",
    "password": "M@45mtg$",
    "username": "mattis",
    "address": "Mannerheimintie 14, 00100 Helsinki",	
    "age": 24
}

###

DELETE http://127.0.0.1:4000/users/1


###

POST http://127.0.0.1:4000/users?admin=true
Content-Type: application/json

{
  "name": "Test Admin",
    "password": "Abcd",
    "username": "admin",
    "address": "Mannerheimintie 11, 00100 Helsinki",	
    "age": 30
}